language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
after_success:
  - .utility/push-javadoc-to-gh-pages.sh
env:
  global:
    secure: E2giRVDokCI21h45o6SAe+AGBr38xb0GxZO5icsM11dV17eG97TxsFM2Eb165tIwhdH0aE3us1VoJ7Ptqu4Dx8AEaLFK1F770yDRdAr8lZpb7zKOO/1SxtWDPaZ7WR/HfvuZuDyThxHdMnOWjN86i11REn7aRNH5qjDrflf7tLt8dZ6H2Vfq0roX6AOmLT6O1/Jz6WXUiP230kQmoQN0rQoBoM3TyMZ5Cjum52uU/gtJHkwpC+3TpxboCp1ntWm2p1LPcIZ/FyyOYaxY4I+P24O+L2ItX7Fgjvfrx8sBbMUcYixLhwn4BHJuz3nPc0nYTKq2/8fhs7Hef4JqkLjXdgre8vDlmMQWp32fs4abeUHAsCM+bWjNcxSAPzVkAMnk9rAJrK39CBEMAkWYzn1R7byjVEQk7n24LZ9vnI2+0eWPAsktjf0I+AUR+KnDz/3ZzOEWdxHbjFCUUMaRm7tQ5aiKGcZmRPuSR9Pg2fb4efEmZyNhDe7QHCoB/PJw7aH23SBwdICuWp6UtigcsNbUeSmAUfIkpUEE8yzd6fW3i8qznvZdtd23Oelymm1Fs7HoqPA5CZ9ty2aiyBlS1K2ZmZfHkfPZlBJ5zWPejQnrZEnNnJovfJbuXUJWwN+K3X9qJzK/bBapklXQ+PtwFTqiiZV8bYkdxGfemd0kNWN3biE=
